PMG.App/Controllers/FactsController.cs
namespace PMG.App.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using PMG.App.Models.Facts;
    using PMG.Services.Fact;
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public class FactsController : Controller
    {
        private readonly IFactService factService;
        private Random random;

        public FactsController(IFactService factService)
        {
            this.factService = factService;
            random = new Random();
        }

        public IActionResult Facts()
        {
            var facts = new Dictionary<string, IFacts>();

            var philosophy = factService.GetPhilosophyFacts()
                .GetAwaiter()
                .GetResult()
                .Select(f => new PhilosophyBindingModel
                {
                    Content = f.Content,
                    Author = f.Author
                })
                .ToList();

            IFacts philosophyFact = philosophy[1];

            facts["Philosophy"] = philosophyFact;

            return View(facts);
        }
        public IFacts GetPhilosophyFact()
        {
            var philosophy = factService
                .GetPhilosophyFacts()
                .GetAwaiter()
                .GetResult()
                .Select(f => new PhilosophyBindingModel
                {
                    Content = f.Content,
                    Author = f.Author
                })
               .ToList();

            var philosophyIndex = random.Next(1, philosophy.Count());

            return philosophy[philosophyIndex];
        }
    }
}

PMG.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PMG.App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img src="~/Images/973_logo.jpg" style="width:40px; height:40px"></a>
            <a class="navbar-brand" asp-controller="About us" asp-action="AboutUs"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Facts" asp-action="Facts">Facts </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="AboutUs" asp-action="AboutUs">AboutUs </a>
                        </li>
                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Admin" asp-action="Create">Create</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Teacher"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Teacher" asp-action="Marks">Input Marks</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Student"))
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Student" asp-action="Bookmark">My Bookmark</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        @if (!this.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" href="/Identity/Account/Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Identity/Account/Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Hello @this.User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Identity/Account/Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>